#!/usr/bin/env python3
"""Which of the renderer's functions the compiler left standing, against a committed list.

A `static` function that gets inlined disappears from the object file; one that stops
being inlined appears in it. Either way round the generated code changes shape, and on
this renderer that is worth microseconds a line rather than bytes:

  - inlined, `f18a_tile_layer_scan_line` folds `config` to a constant and every field it
    reads is an immediate. Out of line the same fields are loads, twice a scanline.
  - out of line, `tmsCopyAlignMask` is one copy of a long straight-line word copy. Inlined
    it is two, inside the scanline body, and costs more than the call it saved.

Neither is visible in a diff, in a size report, or to any test that only checks pixels -
adding a single statement to a function is enough to flip one. This compares the set of
functions the ARM build actually emitted against `baselines/inlining-<tier>.txt` and says
which way each one moved.

    python inlining.py                  both tiers
    python inlining.py --update         re-bless, after reviewing what moved

Maintained by review, not by hand: the file is generated, so a legitimate change (a
function added, removed or renamed) is re-blessed with --update, and anything else is the
gate doing its job. To hold a decision permanently, mark the function - PICO9918_INLINE_HOT
to keep it inlined, PICO9918_NOINLINE to keep it out of line - and the compiler stops
having an opinion. That is the fix for every finding here, so the list only ever holds
functions nobody has needed to pin yet.
"""

import argparse
import glob
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
BASELINES = os.path.join(HERE, "baselines")

# the renderer, and the two files that share its scanline. Each is one translation unit,
# so its object file holds exactly the functions it emitted and nothing of the SDK's.
UNITS = ["pico9918.c", "pico9918_frame.c"]

TIERS = {
    "rp2040": "build-live/pico9918",
    "rp2350": "build-live/pico9918pro",
}

NM = os.environ.get(
    "ARM_NM",
    os.path.expanduser("~/.pico-sdk/toolchain/14_2_Rel1/bin/arm-none-eabi-nm"))

# gcc appends these when it specialises a function; the base name is what identifies it
CLONE_SUFFIX = re.compile(r"\.(constprop|isra|part|cold|lto_priv)\.\d+$")


def objects(tier_dir):
    """The object files for UNITS, wherever CMake put them."""
    found = {}
    for unit in UNITS:
        hits = glob.glob(os.path.join(ROOT, tier_dir, "**", unit + ".obj"), recursive=True)
        hits += glob.glob(os.path.join(ROOT, tier_dir, "**", unit + ".o"), recursive=True)
        if hits:
            found[unit] = hits[0]
    return found


def emitted(obj):
    """Function symbols the object file defines, clone suffixes folded away."""
    out = subprocess.run([NM, "--defined-only", obj], capture_output=True, text=True)
    if out.returncode:
        raise SystemExit("nm failed on %s:\n%s" % (obj, out.stderr.strip()))
    names = set()
    for line in out.stdout.splitlines():
        parts = line.split()
        # "<addr> <type> <name>", and only code symbols
        if len(parts) == 3 and parts[1] in ("t", "T"):
            names.add(CLONE_SUFFIX.sub("", parts[2]))
    return names


def baseline_path(tier):
    return os.path.join(BASELINES, "inlining-%s.txt" % tier)


def read_baseline(tier):
    path = baseline_path(tier)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return {line.strip() for line in f if line.strip() and not line.startswith("#")}


def write_baseline(tier, names):
    os.makedirs(BASELINES, exist_ok=True)
    with open(baseline_path(tier), "w", encoding="utf-8", newline="\n") as f:
        f.write("# Functions the %s build emits from %s.\n"
                "# Generated by inlining.py --update. A name here is out of line; a name\n"
                "# missing is inlined into its callers. See inlining.py for why that matters.\n"
                % (tier, ", ".join(UNITS)))
        for n in sorted(names):
            f.write(n + "\n")


def report(elf=None):
    """The runner's non-fatal view, for the image it just programmed.

    Silent unless something moved, and never raises: a desktop run has no ARM objects,
    a fresh clone has no baseline, and neither is a reason to stop a measurement."""
    try:
        tiers = {t: d for t, d in TIERS.items()
                 if elf is None or os.path.normpath(d) in os.path.normpath(str(elf))}
        failures, _ = run(False, strict=False, tiers=tiers or TIERS)
    except Exception:
        return
    for f in failures:
        if not f.endswith("--update"):
            print("  inlining moved: " + f)
    if failures:
        print("  these numbers carry that - see test/live/inlining.py\n")


def run(update, strict=True, tiers=None):
    failures, notes = [], []

    for tier, tier_dir in (tiers or TIERS).items():
        objs = objects(tier_dir)
        missing = [u for u in UNITS if u not in objs]
        if missing:
            if not strict:
                continue
            raise SystemExit(
                "no object file for %s under %s - build the firmware for this tier first "
                "(ninja -C %s)" % (", ".join(missing), tier_dir, tier_dir))

        names = set()
        for obj in objs.values():
            names |= emitted(obj)

        if update:
            write_baseline(tier, names)
            print("   %-8s blessed %d functions" % (tier, len(names)))
            continue

        want = read_baseline(tier)
        if want is None:
            failures.append("%s: no baseline - run inlining.py --update" % tier)
            continue

        appeared = sorted(names - want)
        vanished = sorted(want - names)
        for n in appeared:
            failures.append("%s: %s is now emitted - it stopped being inlined. If it should "
                            "stay inlined, mark it PICO9918_INLINE_HOT" % (tier, n))
        for n in vanished:
            failures.append("%s: %s is gone - it is now inlined into its callers. If it should "
                            "stay out of line, mark it PICO9918_NOINLINE" % (tier, n))
        if not appeared and not vanished:
            notes.append("%s: %d functions, all where the baseline puts them" % (tier, len(names)))

    return failures, notes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--update", action="store_true",
                    help="re-bless the baselines from the current build")
    args = ap.parse_args()

    failures, notes = run(args.update, strict=True)
    for n in notes:
        print("   " + n)
    for f in failures:
        print("   " + f)
    if failures:
        print("\nFAILED\n  inlining: %d change(s)" % len(failures))
        return 1
    if not args.update:
        print("\nPASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
