# img2carray.py
#
# Convert image files into C arrays for the pico9918-core overlay assets.
#
# Copyright (c) 2023 Troy Schrapel
#
# This code is licensed under the MIT license
#
# https://github.com/visrealm/pico-56
#
# Vendored from the pico9918 firmware so the library builds standalone. The one
# behavioural difference from the firmware copy: palettes are emitted as
# PICO9918_PIXEL_T entries initialized through PICO9918_PIXEL_FROM_RGB12(...), so the
# generated asset carries no host pixel format at all - the platform's policy
# macro converts it, constant-folded at compile time.
#
# The macro's input contract is a *pram entry*: canonical RGB444 byte-swapped,
# i.e. 0xGB0R (bits 15-12 G, 11-8 B, 7-4 zero, 3-0 R). That is what encodePramHex
# emits. See src/platform/pico/platform_pico.h for why the mask in that
# macro is load-bearing, and why the top nibble must be zero (the RP2040
# CRT-scanline dim shifts unmasked, so anything in bit 12 bleeds into blue's MSB).
#

import os
import sys
import glob
import re
import argparse
from PIL import Image


def main() -> int:
    """
    main program entry-point
    """
    parser = argparse.ArgumentParser(
        description='Convert images into C-style arrays for use with the PICO-56.',
        epilog="GitHub: https://github.com/visrealm/pico-56")
    parser.add_argument('-v', '--verbose',
                        help='verbose output', action='store_true')
    parser.add_argument(
        '-p', '--prefix', help='array variable prefix', default='')
    parser.add_argument(
        '-s', '--symbol', help='array variable base name, replacing the one derived '
                               'from the input filename (single input file only)')
    parser.add_argument(
        '-o', '--out', help='output file - defaults to base input file name with .c extension')
    parser.add_argument('-r', '--ram', nargs='+', default='',
                        help='input file(s) to store in Pi Pico RAM - can use wildcards')
    parser.add_argument('-i', '--in', nargs='+', default='',
                        help='input file(s) to store in Pi Pico ROM - can use wildcards')
    args = vars(parser.parse_args())

    outSourceFileName = args['out']
    outSourceFile = None
    outHeaderFileName = ''
    outHeaderFile = None

    inRomFileNames = []
    inRamFileNames = []

    for inRomGlob in args['in']:
        for inRomFileName in glob.glob(inRomGlob):
            inRomFileNames.append(inRomFileName)

    for inRamGlob in args['ram']:
        for inRamFileName in glob.glob(inRamGlob):
            inRamFileNames.append(inRamFileName)

    # --symbol names one array, so more than one input would emit duplicate
    # symbols. Fail loudly rather than produce a file the linker rejects.
    if args['symbol'] and len(inRomFileNames) + len(inRamFileNames) != 1:
        raise SystemExit("--symbol requires exactly one input file, got "
                         + str(len(inRomFileNames) + len(inRamFileNames)))

    if outSourceFileName:
        outSourceFile = open(outSourceFileName, "w")
        outHeaderFileName = os.path.splitext(outSourceFileName)[0] + ".h"
        outHeaderFile = open(outHeaderFileName, "w")

        outSourceFile.write(getFileHeader(
            outSourceFileName, inRomFileNames, inRamFileNames, args, isHeaderFile=False))
        outHeaderFile.write(getFileHeader(
            outHeaderFileName, inRomFileNames, inRamFileNames, args, isHeaderFile=True))

    for infile in inRamFileNames:
        processImageFile(infile, outSourceFile,
                         outHeaderFile, args, inRam=True)

    for infile in inRomFileNames:
        processImageFile(infile, outSourceFile,
                         outHeaderFile, args, inRam=False)

    outSourceFile.close()
    outHeaderFile.close()

    fileList = ""
    for infile in inRamFileNames:
        fileList += os.path.split(infile)[1] + " (RAM), "
    for infile in inRomFileNames:
        fileList += os.path.split(infile)[1] + ", "

    print(sys.argv[0] + " generated C image arrays in " +
          os.path.join(os.getcwd(), outSourceFile.name) + " from (" + fileList.rstrip(", ") + ")")

    return 0


def getFileHeader(fileName, romFileList, ramFileList, args, isHeaderFile) -> str:
    """
    write the header at the top of the .c/.h file
    """
    # Deliberately no timestamp, no cwd and no argv echo: this output is a build
    # artifact, and any of those makes regeneration non-reproducible (the library
    # gates on generated output in CI, and absolute paths leak the build machine's
    # layout into committed-looking source). The source image names below are the
    # provenance that actually matters.
    hdrText = (
        f"/*\n"
        f" * Image file generated by {os.path.split(sys.argv[0])[1]}\n"
        f" * Copyright (c) Troy Schrapel\n"
        f" *\n"
        f" * DO NOT EDIT - regenerate from the source image instead.\n"
        f" *\n"
        f" * Contains the following images:\n"
        f" *\n")

    for infile in ramFileList:
        hdrText += f" * - {os.path.split(infile)[1]} (RAM)\n"

    for infile in romFileList:
        hdrText += f" * - {os.path.split(infile)[1]}\n"

    hdrText += " */\n\n"

    if isHeaderFile:
        hdrText += f"#pragma once\n"
    hdrText += "#include <inttypes.h>\n"
    # The platform dispatch header supplies PICO9918_PIXEL_T /
    # PICO9918_PIXEL_FROM_RGB12 and, off-target, the __aligned fallback that used to
    # come from pico.h. One include covers both platforms, and a host overriding
    # the pixel policy is honoured here too.
    hdrText += "#include \"impl/platform.h\"\n"
    # The palette arrays are PICO9918_PIXEL_T. One width ships, but the policy is
    # host-overridable, and the array is compiled into the library - so a consumer
    # TU that does not have the same policy in effect would silently misread it:
    # wrong element size, wrong stride, reads past the end. There is no link error
    # for that, so pin it: the library stamps the width it built with, and any
    # consumer disagreeing fails to compile instead of rendering garbage.
    hdrText += (
        "\n/* Pixel-policy width guard - see the note in img2carray.py. */\n"
        "#ifdef PICO9918_ASSET_PIXEL_SIZE\n"
        "_Static_assert(sizeof(PICO9918_PIXEL_T) == PICO9918_ASSET_PIXEL_SIZE,\n"
        "               \"PICO9918_PIXEL_T differs from the width these generated \"\n"
        "               \"assets were built with - the pixel policy must match \"\n"
        "               \"the library's - see platform/)\");\n"
        "#endif")
    return hdrText


def encodePramHex(r, g, b) -> str:
    """
    encode 8-bit r, g, b into a pram entry: canonical RGB444 (0x0RGB) byte-swapped
    to 0xGB0R, which is PICO9918_PIXEL_FROM_RGB12's documented input order. Bits 7-4
    are left zero - the macro refills them from green.
    """
    c = ((int(g) // 16) & 0xf) << 12
    c |= ((int(b) // 16) & 0xf) << 8
    c |= ((int(r) // 16) & 0xf)
    return "{0:#0{1}x}".format(c, 6)


def paletteArrayString(pal) -> str:
    """
    convert a palette list into an array string of PICO9918_PIXEL_FROM_RGB12
    initializers over pram-order values (see encodePramHex)
    """
    paletteValues = []
    for i in range(0, len(pal), 3):
        paletteValues.append("PICO9918_PIXEL_FROM_RGB12(" + encodePramHex(
            pal[i], pal[i + 1], pal[i + 2]) + ")")
    return "{" + ", ".join(paletteValues) + "}"


def generateArrayComment(infile, src, bpp) -> str:
    """
    generate a comment block for an image giving some metadata
    """
    comment = "\n\n/* source: " + infile + "\n"
    comment += " * size  : " + \
        str(src.width) + "px x " + str(src.height) + "px\n"
    comment += " *       : " + \
        str(int(src.width * src.height * bpp / 8)) + " bytes\n"

    if src.palette:
        comment += " * format: PICO9918_PIXEL_T palette (pram-order RGB444 via " \
            "PICO9918_PIXEL_FROM_RGB12), " + str(bpp) + "bpp indexed image\n */\n"
    else:
        comment += " * format: 16bpp abgr image\n */\n"
    return comment


def generateProto(varName, src, inRam, isHeader) -> str:
    """
    generate an array prototype (or definition)
    """
    typePrefix = ("extern " if isHeader else " ")
    varNamePrefix = "" if isHeader else (
        "__aligned(4) " + ("" if inRam else "__in_flash() "))
    dataType = "uint8_t " if src.palette else "uint16_t "
    suffix = ";" if isHeader else " = "
    proto = ""

    # if the image has a palette, output that first
    if src.palette:
        proto = typePrefix + "PICO9918_PIXEL_T " + varNamePrefix + varName + "_pal[]" + suffix
        if not isHeader:
            proto += paletteArrayString(src.palette.tobytes()) + ";"
        proto += "\n"

    # output the image array prototype
    proto += typePrefix + dataType + varNamePrefix + varName + "[]" + suffix
    if isHeader:
        # Dimensions as macros AND as the historical const ints. The macros are
        # the ones to use: reading a `const int` object is not an arithmetic
        # constant expression in standard C, so it cannot initialise a static
        # (GCC allows it as an extension, MSVC rejects it with C2099 - and the
        # splash overlay's logoOffset needs exactly that). The const ints stay
        # for existing callers.
        proto += "\n#define " + varName.upper() + "_WIDTH  " + str(src.width) + "\n"
        proto += "#define " + varName.upper() + "_HEIGHT " + str(src.height) + "\n"
        proto += "const int " + varNamePrefix + varName + \
            "Width = " + str(src.width) + ";\n"
        proto += "const int " + varNamePrefix + varName + \
            "Height = " + str(src.height) + ";\n"
    return proto


def imageToArrayContents(src, pix, bpp) -> str:
    """
    return a string containing a c-style array of the image pixels
    """
    rows = []
    for y in range(src.height):
        row = []
        value = 0
        for x in range(src.width):
            col = pix[x, y]
            if hasattr(col, "__len__"):
                # Non-palettized (truecolour) source. The palette path emits
                # PICO9918_PIXEL_FROM_RGB12(...) so no generated asset carries a
                # host pixel format, but this path would write raw ABGR16
                # straight into a uint16_t array - the exact thing
                # PICO9918_PIXEL_FROM_RGB12 exists to avoid. No asset uses it
                # today, so rather than ship a silent trap for whoever drops in
                # the first truecolour PNG, refuse.
                # Making it emit pixel-policy initializers is a small change;
                # it just needs a caller and a test to justify it.
                raise SystemExit(
                    "img2carray: truecolour (non-palettized) images are not "
                    "supported - convert to an indexed PNG, or extend this "
                    "path to emit PICO9918_PIXEL_FROM_RGB12(...) initializers "
                    "like paletteArrayString does.")
            elif bpp == 8:
                row.append("{0:#0{1}x}".format(col, 4))
            elif bpp == 4:
                value = value | col
                if (x & 1):
                    row.append("{0:#0{1}x}".format(value, 4))
                    value = 0
                else:
                    value <<= bpp
            elif bpp == 2:
                value = value | col
                if (x & 3) == 3:
                    row.append("{0:#0{1}x}".format(value, 4))
                    value = 0
                else:
                    value <<= bpp
            else:  # 1bpp
                value = value | col
                if (x & 7) == 7:
                    row.append("{0:#0{1}x}".format(value, 4))
                    value = 0
                else:
                    value <<= bpp

        rows.append(", ".join(row))
    return "\n  " + (",\n  ".join(rows))


def processImageFile(infile, srcOutput, hdrOutput, args, inRam) -> None:
    """
    process a single image and output it to the header and source files
    """
    outPathWithoutExt = os.path.splitext(infile)[0]
    closeFile = False
    if srcOutput == None:
        srcOutput = open(outPathWithoutExt + ".c", "w")
        srcOutput.write(getFileHeader(srcOutput.name, [] if inRam else [infile], [
                        infile] if inRam else [], args, isHeaderFile=False))
        hdrOutput = open(outPathWithoutExt + ".h", "w")
        hdrOutput.write(getFileHeader(hdrOutput.name, [] if inRam else [infile], [
                        infile] if inRam else [], args, isHeaderFile=True))
        closeFile = True

    # --symbol names the array directly, so a board-conditional asset
    # (splash_pro.png) can still produce the canonical `splash` symbols and the
    # consuming TU needs no #ifdef alias block.
    varName = args.get('symbol') or os.path.splitext(os.path.split(infile)[1])[0]
    varName = re.sub('[^0-9a-zA-Z]+', '', args['prefix'] + varName)

    try:
        src = Image.open(infile)
        pix = src.load()

        bpp = 16
        if src.palette:
            if len(src.palette.tobytes()) <= (2 * 3):
                bpp = 1
            elif len(src.palette.tobytes()) <= (4 * 3):
                bpp = 2
            else:
                bpp = 4 if len(src.palette.tobytes()) <= (16 * 3) else 8

        comment = generateArrayComment(infile, src, bpp)

        hdrOutput.write(comment)
        hdrOutput.write(generateProto(
            varName, src, inRam, isHeader=True) + "\n")

        srcOutput.write(comment)
        srcOutput.write(generateProto(
            varName, src, inRam, isHeader=False) + "{")
        srcOutput.write(imageToArrayContents(src, pix, bpp) + "};")

        src.close()

    except IOError as e:
        # Do not swallow this: returning 0 with a stub header makes the C build
        # fail later on undeclared symbols, pointing at the consumer instead of
        # at the unreadable image.
        raise SystemExit("img2carray: cannot convert " + infile + ": " + str(e))

    if closeFile:
        srcOutput.close()
        hdrOutput.close()

    return


# program entry
if __name__ == "__main__":
    sys.exit(main())
