
' ===============================
  GOTO CONFTOOL_START
firmwareFilename:
  DATA BYTE "pico9918-vga-build-v1-2-diag.uf2"


  CONST #FIRMWARE_BLOCKS = 249
  CONST FIRMWARE_BANKS = 10
  CONST FIRMWARE_BLOCKS_PER_BANK = 27
  CONST FIRMWARE_MAJOR_VER = 1
  CONST FIRMWARE_MINOR_VER = 2
  CONST #FIRMWARE_YEAR = 2024
  CONST FIRMWARE_MONTH = 12
  CONST FIRMWARE_DAY = 15


CONFTOOL_START:
 