#
# Project: pico9918
#
# Generate CVBasic CONST declarations for the config-byte layout
#
# Copyright (c) 2025 Troy Schrapel
#
# This code is licensed under the MIT license
#
# https://github.com/visrealm/pico9918
#
# Parses the pico9918_config_option_t enum out of the library's authoritative
# pico9918_config.h and emits the same names/values as CVBasic constants,
# so the configurator never re-declares a config byte index.
#

import os
import re
import sys
import argparse


ENUM_RE = re.compile(
    r"typedef\s+enum\s*\{(?P<body>.*?)\}\s*pico9918_config_option_t\s*;",
    re.DOTALL)

ENTRY_RE = re.compile(
    r"^\s*(?P<name>PICO9918_CONF_[A-Z0-9_]+)\s*=\s*(?P<expr>[^,/]+?)\s*,?"
    r"\s*(?://\s*(?P<comment>.*?))?\s*$")


def parseEnum(headerText):
    """
    return [(name, value, comment)] in declaration order
    """
    match = ENUM_RE.search(headerText)
    if not match:
        raise ValueError("pico9918_config_option_t enum not found")

    values = {}
    entries = []

    for line in match.group('body').splitlines():
        # strip standalone comment lines ("// 21-127: free" etc.)
        if not line.strip() or line.strip().startswith('//'):
            continue

        entry = ENTRY_RE.match(line)
        if not entry:
            raise ValueError("unparsed enum line: " + line.strip())

        name = entry.group('name')
        # resolve symbolically - entries may reference earlier ones
        # (e.g. PICO9918_CONF_PALETTE_IDX_0 + 32)
        value = eval(entry.group('expr'), {"__builtins__": {}}, dict(values))
        values[name] = value
        entries.append((name, value, entry.group('comment')))

    return entries


def writeBas(outFileName, headerFileName, entries):
    """
    write the CVBasic source file. LF endings, declaration order
    """
    lines = [
        "' Auto-generated by {0} - do not edit.".format(
            os.path.basename(sys.argv[0])),
        "' Source: {0}".format(os.path.basename(headerFileName)),
        "'",
        "' The config-byte ABI is owned by that header. To add or change a",
        "' byte, edit it there and rebuild.",
        "",
    ]

    width = max(len(name) for name, _, _ in entries)

    for name, value, comment in entries:
        line = "CONST {0} = {1}".format(name.ljust(width), value)
        if comment:
            line += "  ' " + comment
        lines.append(line)

    with open(outFileName, mode='w', newline='\n') as out:
        out.write("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Generate CVBasic config-byte constants from the '
                    'pico9918-core config header.',
        epilog="GitHub: https://github.com/visrealm/pico9918")
    parser.add_argument('-o', '--outfile', help='output .bas file',
                        required=True)
    parser.add_argument('header', help='path to pico9918_config.h')
    args = vars(parser.parse_args())

    with open(args['header'], mode='r') as header:
        entries = parseEnum(header.read())

    writeBas(args['outfile'], args['header'], entries)

    print("Generated {0} config constants in {1}".format(
        len(entries), args['outfile']))

    return 0


# program entry
if __name__ == "__main__":
    sys.exit(main())
