/*
 * Project: pico9918
 *
 * Copyright (c) 2024 Troy Schrapel
 *
 * This code is licensed under the MIT license
 *
 * https://github.com/visrealm/pico9918
 *
 *
 * PICO9918 tier-1 host ops.
 *
 * This is the firmware's ops header. The library's pico platform header pulls it
 * in via PICO9918_HOST_OPS_HEADER (set from the root CMakeLists), so every macro
 * here expands INSIDE the library TU that needs it - no function pointer, no
 * cross-TU call, neither of which belongs on a per-scanline path.
 *
 * Everything referenced here stays firmware-owned. The library never declares
 * this state; it only expands the macros.
 *
 * Do not include this directly from firmware code - main.c gets it through the
 * library's platform dispatch header, so there is exactly one definition site.
 */

#pragma once

/* Announce ourselves to the library's interlock. The platform header hard-errors
   on a Pico build that does not see this, which is what makes "the ops header was
   shadowed by a same-named file" and "the -D was never passed" loud failures
   instead of a silent downgrade to no-op ops. Do not remove or rename without
   changing the check in impl/platform.h. */
#define PICO9918_HOST_OPS_SUPPLIED 1

/* Deliberately does NOT include gpio.h, and nothing here needs a GPIO_* symbol.
   gpio.h includes the generated tms9918.pio.h, and this header reaches 6 of the
   library's 7 TUs via Priv.h - which would give the library objects a dependency on
   a header generated by a custom command attached to the FIRMWARE target, with no
   build-order edge between them. With .ninja_deps wiped, a cold build then fails
   with "tms9918.pio.h: No such file or directory"; a clean build survives only
   because ninja happens to schedule the generator early. Do not add it back. */
#include "hardware/irq.h"
#include "hardware/pio.h"
#include "hardware/sync.h"   /* __dmb() - the barrier in the critical section */


/* PIO and IRQ resources for the TMS9918 <-> CPU interface. They live here because
   the tier-1 ops below need them and those ops expand in library TUs.

   The state-machine indices are MACROS, not `extern const uint`. They are fixed
   hardware wiring, and the difference is measurable: an extern is opaque to the
   library TU, so pio_sm_put() can no longer fold to a single store at a
   compile-time txf offset and emits a load plus three-instruction address
   computation instead (verified in the disassembly). */
#define TMS_PIO pio1

#define TMS_WRITE_IRQ PIO1_IRQ_0
#define TMS_READ_IRQ  PIO1_IRQ_1

#define tmsWriteSm 0u
#define tmsReadSm  1u

/* TMS9918A read-ahead value - firmware-owned, pushed to the read PIO by
   PICO9918_HOST_STATUS_VISIBLE(). Not static: the macro has to inline fully into
   the library TU that expands it. */
extern uint8_t nextValue;


/*
 * Tier-1 host op: critical section around the frame module's interrupt/status
 * update.
 *
 * THE __dmb() PLACEMENT IS ASYMMETRIC ON PURPOSE. In ENTER the barrier comes
 * AFTER both irq_set_enabled(false) calls; in EXIT it comes BEFORE both
 * irq_set_enabled(true) calls. That puts it on the INSIDE edge of the critical
 * window at both ends, which is what stops accesses inside the window from being
 * hoisted above the close or sunk past the re-open. Making this symmetrical
 * leaves one edge unguarded - do not "tidy" it.
 *
 * The "memory" clobber inside __dmb() is the load-bearing half: these expand in a
 * library TU where the frame interrupt state is not volatile, so it is the clobber -
 * not the hardware barrier - that forces it to memory before the PIO IRQs re-open.
 *
 * Two caveats: this is disable/enable, not save/restore, so it is not nestable and
 * is valid only from core-1 thread context; and it does not mask IO_IRQ_BANK0, so
 * the reset GPIO IRQ can still preempt the window.
 */
#define PICO9918_HOST_ENTER_CRITICAL() \
  do { \
    irq_set_enabled(TMS_WRITE_IRQ, false); \
    irq_set_enabled(TMS_READ_IRQ, false); \
    __dmb(); \
  } while (0)

#define PICO9918_HOST_EXIT_CRITICAL() \
  do { \
    __dmb(); \
    irq_set_enabled(TMS_WRITE_IRQ, true); \
    irq_set_enabled(TMS_READ_IRQ, true); \
  } while (0)


/*
 * Tier-1 host op: publish the status/read-ahead word to the read PIO.
 *
 * The read SM is
 * pre-loaded with the byte the host CPU would receive next, so a /CSR must be
 * serviceable with no CPU-side latency - which is why this cannot be a call.
 *
 * NOTE - the gate is raw `tms9918->isUnlocked`, NOT the base-aware
 * pico9918_status_select_active(). That is deliberate and stays that way: the word
 * pushed here is host PIO policy, not a library decision about which status
 * register is selected.
 */
#define PICO9918_HOST_STATUS_VISIBLE() \
  do { \
    uint32_t readAhead = 0xff;              /* pin direction */ \
    readAhead |= nextValue << 8; \
    if (tms9918->isUnlocked) \
    { \
      int vr = TMS_REGISTER(tms9918, 0x0F) & 0x0F; \
      readAhead |= (TMS_STATUS(tms9918, vr)) << 16; \
      readAhead |= vr << 24; \
    } \
    else \
    { \
      readAhead |= (TMS_STATUS(tms9918, 0)) << 16; \
    } \
    pio_sm_put(TMS_PIO, tmsReadSm, readAhead); \
  } while (0)


/*
 * Per-scanline capture seams for test/live (PICO9918_LIVE_TEST builds only).
 *
 * The library expands these on the scanline path, so they are declared here
 * rather than included: livetest.h needs the library's own SCANLINE_BYTES_MAX to
 * size its buffer, and this header is reached FROM the library headers that
 * define it. The definitions and the capture buffer live in livetest.c.
 */
#if PICO9918_LIVE_TEST

/** \brief  capture a scanline, before the line buffer is reused
 *  \param  y       the row
 *  \param  height  the frame's own height, not the last row reached
 *  \param  width   pixels in the row
 *  \param  indices the rendered line, word-aligned
 */
void liveTestCaptureRow(uint16_t y, uint16_t height, uint16_t width, const uint8_t* indices);

/** \brief record a display row and what it cost in microseconds; a gap in \p y is a dropped row */
void liveTestNoteRow(uint16_t y, uint32_t us);

/** \brief wait for the capture DMA, which must finish before the line buffer is written again */
void liveTestCaptureWait(void);

#define PICO9918_LINE_CAPTURE_WAIT() liveTestCaptureWait()
#define PICO9918_LINE_CAPTURE(y, height, width, indices) \
  liveTestCaptureRow((y), (height), (width), (indices))
#define PICO9918_LINE_NOTE_TIME(y, us) liveTestNoteRow((y), (us))

#endif /* PICO9918_LIVE_TEST */
